### ISSUE TITLE
Call the Bridge from the SubgraphOperator Fusion pass

### ISSUE THREAD

**Issue by mbrookhart** [NervanaSystems/ngraph-mxnet#288]
Remove the direct integration into GraphExecutor in favor of fusion via the subgraph operator passes

Acceptance Criteria:
1. Unit tests pass
2. No performance degredation in deepmark.

**Comment by ashokei** [comment]
adding notes
```

**Comment by ashokei** [comment]
when subgraph api adds shape/type awareness to partition pass, we can replace our identification to use that directly (instead of our current bind/simple_bind mod).

"Executor/cached op call Subgraph Partition pass, this does nnvm::Node labeling, use MXNet’s subgraph partition algorithm, passes the subgraph to the bridge, compilation in the bridge (but just parse/compile, no subgraph identification), and then embedding ngraph_subgraph_operator in the returned graph"

"to keep it modular we can separate partition (which will come with shape/type)  and actual ngraph compilation (which is done at cached_op or fstatecreate stage and the compiled ngraph_ persisted in state object). Cached_op allows to mutate state as needed (if shape/type change , etc). (edited)

it looks like they want to add shape/type attrs to nnvm::graph before passing to partition pass. This should help us with bind/simple_bind issue, as we will have shape/type for node labelling in partition pass"

**Comment by mbrookhart** [comment]
Completed by #338
